### PR TITLE
Add Connection Timeout Parameter

### PR DESCRIPTION
**Pull request by miere**
Added ```timeout``` parameter to set a custom timeout value, as discussed at #38 issue.

### CODE REVIEW

**Comment by jamesnetherton** [comment]
@miere @jamezp Any chance this can be rebased so it can get merged???

This change would be useful for me right now.

Cheers.

**Comment by jamezp** [comment]
I've been meaning to process the pull queue and fix this issue, but just haven't had a chance with other deadlines ATM. Maybe I'll get a chance sometime this week or weekend and cut another Alpha release.

**Comment by joeydaowang** [comment]
When could we have release with this change? Really need it.
Thanks.

**Comment by jamezp** [comment]
I'm hoping to get to it this week or next week.

**Comment by jamezp** [comment]
I'm replacing this with https://github.com/wildfly/wildfly-maven-plugin/pull/60 due to the merge conflict.

**Pull request closed without merging**
