### PR TITLE
[WFMP-194] Record versions of manifests used to provision server

### PR DESCRIPTION
**Pull request by spyrkob**
Issue: https://issues.redhat.com/browse/WFMP-194

Requires https://github.com/wildfly-extras/prospero/pull/318 and prospro-metadata update

### CODE REVIEW

**Comment by spyrkob** [comment]
@jfdenise this would record the version of manifests used to provision. If that looks OK I'll try to release prospero Beta7 this week.

**Comment by jfdenise** [comment]
@spyrkob , I suspect tha tthis PR will fail until we release prospero. In which file the versions are stored? Do you have an example of file? Thank-you.

**Comment by spyrkob** [comment]
They're stored in `.installation/manifest_version.yaml` which looks like:
```
---
maven:
- groupId: "org.wildfly.channels"
  artifactId: "wildfly-27.0"
  version: "1.0.0"
```

**Comment by jamezp** [comment]
We will need a JIRA, https://issues.redhat.com/browse/WFMP, too.

**Comment by spyrkob** [comment]
Created the JIRA, I'll update commit description when I push prospero version change

**Comment by jamezp** [comment]
I've merged the channel [upgrade PR](https://github.com/wildfly/wildfly-maven-plugin/pull/305) if that helps this at all.

**Review by jfdenise — APPROVED** [review]

**Comment by jamezp** [comment]
Oh shoot, I created a conflict by merging #306 first. Sorry about that @spyrkob

**Comment by jamezp** [comment]
The latest prospero upgrade fails because of signature mismatches #307

**Pull request merged**
