### PR TITLE
Issue #130: fixed start if already running an instance?

### PR DESCRIPTION
**Pull request by mareknovotny**
this works for me, if you would like to rework it, drop it ;)

### CODE REVIEW

**Comment by jamezp** [comment]
We'd have to check if it's a domain server as you can start either standalone or domain with this goal. I can always have a look at that as well :)

**Comment by mareknovotny** [comment]
@jamezp so is this ok for now?

**Comment by mareknovotny** [comment]
You're welcome! 
Will this fix show up as a SNAPSHOT or real Alpha12 release in maven repository?

**Comment by jamezp** [comment]
I'll try to get a Alpha12 out this week. It's not all the difficult to release.

**Comment by mareknovotny** [comment]
any update on a release?

**Comment by jamezp** [comment]
I'll see if I can't get to it today. I've just got a few other tasks to take care of first.

**Comment by mareknovotny** [comment]
is possible to expect a release this week? just curious.

**Comment by jamezp** [comment]
Yeah the short week got in the way last week. I'll try to get it released today. If not tomorrow for sure.

**Comment by jamezp** [comment]
@mareknovotny 1.1.0.Beta1 has been released.

**Comment by mareknovotny** [comment]
awesome! thanks a lot.

**Pull request merged**
