### PR TITLE
Use prospero BOM to manage shared dependencies

### PR DESCRIPTION
**Pull request by spyrkob**
Uses prospero parent as BOM to allign shared dependency versions

Requires https://github.com/wildfly-extras/prospero/pull/401 

cc @jfdenise

### CODE REVIEW

**Comment by jfdenise** [comment]
@jamezp , I see a benefit to align our provisioning tooling (prospero and this plugin provisioning capabilities). We are quickly becoming out of sync.

**Comment by jamezp** [comment]
I would prefer a separate BOM I guess. It seems odd for the Maven plugin to reply on prospero only provisioning uses it. The deploy goals, CLI goals, etc. do not need provisioning. 

Basically prospero is about channels and not Maven. This project is about Maven and not channels. It feels backwards to me.

**Comment by jmesnil** [comment]
I agree with @jamezp. The provisioning capability of the plug-is one among others and I don't think Prospero should be the component that dictates the plugins dependency updates.

**Comment by spyrkob** [comment]
OK I'll work on separate BOM then, thanks for feedback

**Pull request closed without merging**
