### PR TITLE
Fixes issue 31: WFLYCC0034: Closing leaked controller client after upgrade to 1.1.0.Alpha1

### PR DESCRIPTION
**Pull request by tsegismont**
Fixes issue 31: WFLYCC0034: Closing leaked controller client after upgrade to 1.1.0.Alpha1

### CODE REVIEW

**Comment by tsegismont** [comment]
Hi @jamezp , if you have a few cycles, could you have a look at this PR? Any schedule for the Alpha2? Thanks.

**Comment by jamezp** [comment]
Sorry for the delay. I'll get to it today and possibly cut a release today.

**Comment by jamezp** [comment]
This would definitely work, but I see other places it's abused as well. I'm just going to rework the whole client portion in general. Thanks for the PR though!

**Comment by tsegismont** [comment]
Ok

2015-03-13 21:31 GMT+01:00 James R. Perkins <notifications@github.com>:

**Pull request closed without merging**
