### PR TITLE
Add support for properties files, like the CLI client does.

### PR DESCRIPTION
**Pull request by Jurrie**
In the process, I removed some spurious throws clauses and converted some return types from Collection to List (because a List is ordered).

### CODE REVIEW

**Comment by jamezp** [comment]
We require that all contributions be made under the terms of the MIT License, http://www.opensource.org/licenses/mit-license.php. Do you agree to the these terms?

**Comment by Jurrie** [comment]
Yes, I agree to the MIT License terms.

**Comment by jamezp** [comment]
I think this look good. One concern I do have is since this sets system properties, other plugins/goals that are executed after this will also see the system properties. I may add some code to remove the system properties set after the goal is executed as part of another PR.

And just to reference the JIRA https://issues.jboss.org/browse/WFMP-51.

**Comment by jamezp** [comment]
Just an FYI I've refactor this a bit in https://github.com/wildfly/wildfly-maven-plugin/pull/120. I moved the configuration to be outside the `<execute-commands/>` tag. I'm actually going to [deprecate](https://issues.jboss.org/browse/WFMP-54) the `<execute-commands/>` configuration property.

Basically instead of
```xml
<configuration>
    <execute-commands>
        <propertiesFiles>
            <propertiesFile>some.properties</propertiesFile>
        </propertiesFiles>
    </execute-commands>
</configuration>
```

You'd just do
```xml
<configuration>
    <propertiesFiles>
        <propertiesFile>some.properties</propertiesFile>
    </propertiesFiles>
</configuration>
```

**Pull request merged**
